"""empty message

Revision ID: 7b288853f153
Revises: None
Create Date: 2016-05-05 17:44:32.360543

"""

# revision identifiers, used by Alembic.
revision = '7b288853f153'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('corp_name', sa.String(length=64), nullable=True),
    sa.Column('corp_license_no', sa.String(length=64), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('sub_account_no', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('agency_id'),
    sa.UniqueConstraint('corp_name')
    )
    op.create_table('fees',
    sa.Column('fee_id', sa.Integer(), nullable=False),
    sa.Column('fee_name', sa.String(length=32), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('time_length', sa.Integer(), nullable=True),
    sa.Column('time_length_type', sa.Integer(), nullable=True),
    sa.Column('tickets_no', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('fee_id'),
    sa.UniqueConstraint('fee_name')
    )
    op.create_table('role_groups',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('login_name', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('phone_no', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('id_card_no', sa.String(length=20), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('user_type', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('agency_id', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.agency_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role_groups.role_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_login_name'), 'users', ['login_name'], unique=True)
    op.create_table('fee_records',
    sa.Column('fee_record_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('collector_id', sa.Integer(), nullable=True),
    sa.Column('fee_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('expire_time', sa.DateTime(), nullable=True),
    sa.Column('charge_time', sa.DateTime(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['collector_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['fee_id'], ['fees.fee_id'], ),
    sa.PrimaryKeyConstraint('fee_record_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fee_records')
    op.drop_index(op.f('ix_users_login_name'), table_name='users')
    op.drop_table('users')
    op.drop_table('role_groups')
    op.drop_table('fees')
    op.drop_table('agencies')
    ### end Alembic commands ###
