"""empty message

Revision ID: 99aa0d1dbdcd
Revises: 6b4a381b117b
Create Date: 2016-05-23 08:36:53.968275

"""

# revision identifiers, used by Alembic.
revision = '99aa0d1dbdcd'
down_revision = '6b4a381b117b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('register_state', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'register_state')
    ### end Alembic commands ###
